version: '3'
services:
  db:
    build: ./docker/db
    hostname: db
    tty: true
    privileged: true
    networks:
      envoymesh:
        aliases:
          - db
  special:
    build: ./docker/special
    hostname: special
    tty: true
    privileged: true
    networks:
      envoymesh:
        aliases:
          - special
  restricted:
    build: ./docker/restricted
    hostname: restricted
    tty: true
    privileged: true
    networks:
      envoymesh:
        aliases:
          - restricted
  external:
    build: ./docker/external
    hostname: external
    tty: true
    privileged: true
    networks:
      envoymesh:
        aliases:
          - external
  spire-server:
    build: ./docker/spire-server
    hostname: spire-server
    tty: true
    privileged: true
    networks:
      envoymesh:
        aliases:
          - spire-server
  api-server:
    build:
      context: ./docker/api-server
    networks:
      envoymesh:
        aliases:
          - api-server
    expose:
      - "5000"
    ports:
      - "5000:5000"
networks:
  envoymesh: {}
